
cmake_minimum_required(VERSION 3.10)

project(json-parser VERSION 0.1 LANGUAGES CXX) #this project line also sets PROJECT_SOURCE_DIR

# Require C++17
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

add_executable(lexer lexer.cpp)
add_subdirectory(tests)